import type { Metadata, NextConfig } from "next";
import { Inter as FontSans } from "next/font/google";
import Footer from "@/components/Footer";
import Navbar from "@/components/header/Navbar";
import { cn } from "@/lib/utils";
import TanstackProvider from "@/providers/TanstackProvider";
import "../styles/globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Bluebird - Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen scroll-smooth bg-background font-sans antialiased", fontSans.variable)}>
        <TanstackProvider>
          <Navbar />
          <div className="py-5 text-gray-900">{children}</div>
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
